//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MediaCore {
  public static void gmf_init(int logtype, int loglevel, string logpath) {
    MediaCorePINVOKE.gmf_init(logtype, loglevel, logpath);
  }

  public static void gmf_uninit() {
    MediaCorePINVOKE.gmf_uninit();
  }

  public static void gmf_set_log_func(SWIGTYPE_p_f_int_p_q_const__char__void func) {
    MediaCorePINVOKE.gmf_set_log_func(SWIGTYPE_p_f_int_p_q_const__char__void.getCPtr(func));
  }

  public static SWIGTYPE_p__gmf_player gmf_player_create(string name, string pipelineFile) {
    global::System.IntPtr cPtr = MediaCorePINVOKE.gmf_player_create(name, pipelineFile);
    SWIGTYPE_p__gmf_player ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p__gmf_player(cPtr, false);
    return ret;
  }

  public static void gmf_player_destory(SWIGTYPE_p__gmf_player hPlayer) {
    MediaCorePINVOKE.gmf_player_destory(SWIGTYPE_p__gmf_player.getCPtr(hPlayer));
  }

  public static int gmf_player_open(SWIGTYPE_p__gmf_player hPlayer, string url, SWIGTYPE_p_void hWnd) {
    int ret = MediaCorePINVOKE.gmf_player_open(SWIGTYPE_p__gmf_player.getCPtr(hPlayer), url, SWIGTYPE_p_void.getCPtr(hWnd));
    return ret;
  }

  public static int gmf_player_close(SWIGTYPE_p__gmf_player hPlayer) {
    int ret = MediaCorePINVOKE.gmf_player_close(SWIGTYPE_p__gmf_player.getCPtr(hPlayer));
    return ret;
  }

  public static int gmf_player_play(SWIGTYPE_p__gmf_player hPlayer) {
    int ret = MediaCorePINVOKE.gmf_player_play(SWIGTYPE_p__gmf_player.getCPtr(hPlayer));
    return ret;
  }

  public static int gmf_player_pause(SWIGTYPE_p__gmf_player hPlayer) {
    int ret = MediaCorePINVOKE.gmf_player_pause(SWIGTYPE_p__gmf_player.getCPtr(hPlayer));
    return ret;
  }

  public static int gmf_player_resume(SWIGTYPE_p__gmf_player hPlayer) {
    int ret = MediaCorePINVOKE.gmf_player_resume(SWIGTYPE_p__gmf_player.getCPtr(hPlayer));
    return ret;
  }

  public static int gmf_player_seek(SWIGTYPE_p__gmf_player hPlayer, uint pos) {
    int ret = MediaCorePINVOKE.gmf_player_seek(SWIGTYPE_p__gmf_player.getCPtr(hPlayer), pos);
    return ret;
  }

  public static int gmf_player_rate(SWIGTYPE_p__gmf_player hPlayer, float rate) {
    int ret = MediaCorePINVOKE.gmf_player_rate(SWIGTYPE_p__gmf_player.getCPtr(hPlayer), rate);
    return ret;
  }

}
